# Generated by Django 5.1.1 on 2025-02-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='class_in_grade',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
