# Generated by Django 5.1.1 on 2025-02-24 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Grades', '0002_student_class_in_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='class_in_grade',
        ),
    ]
