# Generated by Django 5.1.1 on 2025-01-29 14:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(5)])),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('main_image_url', models.CharField(blank=True, help_text='URL تصویر اصلی پست', max_length=1024, null=True)),
                ('content', models.JSONField(default=list, help_text='لیستی از محتوای پست شامل متن، تصاویر، ویدیوها و غیره')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('publish_at', models.DateTimeField(blank=True, help_text='تاریخ و زمان انتشار پست', null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
