# Generated by Django 5.1.3 on 2024-11-06 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('WeeklySchedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('national_code', models.CharField(max_length=11, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('role', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('national_code', models.CharField(max_length=11, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('role', models.CharField(max_length=32)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student', to='WeeklySchedule.grade')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
