# Generated by Django 5.1.1 on 2025-01-29 14:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 29, 14, 9, 20, 558688, tzinfo=datetime.timezone.utc)),
        ),
    ]
