# Generated by Django 5.1.1 on 2025-01-30 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_alter_passwordresetcode_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 30, 10, 47, 32, 417947, tzinfo=datetime.timezone.utc)),
        ),
    ]
