# Generated by Django 5.1.1 on 2024-12-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_emailverificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationcode',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='emailverificationcode',
            name='code',
            field=models.CharField(max_length=64),
        ),
    ]
