# Generated by Django 5.1.1 on 2024-12-09 07:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0004_passwordresetcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 9, 7, 43, 0, 955650, tzinfo=datetime.timezone.utc)),
        ),
    ]
