# Generated by Django 5.1.1 on 2025-02-02 20:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0004_alter_passwordresetcode_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 2, 20, 38, 44, 46762, tzinfo=datetime.timezone.utc)),
        ),
    ]
