# Generated by Django 5.1.1 on 2025-02-24 14:21

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0005_alter_passwordresetcode_expires_at'),
        ('WeeklySchedule', '0003_grade_class_in_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbase',
            name='class_in_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='WeeklySchedule.grade'),
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 24, 14, 26, 11, 83505, tzinfo=datetime.timezone.utc)),
        ),
    ]
