# Generated by Django 5.1.1 on 2025-02-24 19:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0010_alter_passwordresetcode_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbase',
            name='is_blog_admin',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 24, 19, 34, 37, 842436, tzinfo=datetime.timezone.utc)),
        ),
    ]
