# Generated by Django 5.1.1 on 2025-02-24 20:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0011_userbase_is_blog_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 24, 20, 19, 31, 549489, tzinfo=datetime.timezone.utc)),
        ),
    ]
