# Generated by Django 5.1.1 on 2025-02-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeeklySchedule', '0002_alter_grade_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='class_in_grade',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('ریاضی', 'ریاضی'), ('تجربی', 'تجربی')], max_length=15, null=True),
        ),
    ]
