# Generated by Django 5.1.1 on 2025-02-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeeklySchedule', '0003_grade_class_in_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='name',
            field=models.CharField(choices=[('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=2),
        ),
    ]
