# Generated by Django 5.1.1 on 2025-02-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeeklySchedule', '0004_alter_grade_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='class_in_grade',
        ),
        migrations.AlterField(
            model_name='grade',
            name='name',
            field=models.CharField(choices=[('7/1', '7/1'), ('7/2', '7/2'), ('8/1', '8/1'), ('8/2', '8/2'), ('9/1', '9/1'), ('9/2', '9/2'), ('10/ریاضی', '10/ریاضی'), ('10/تجربی', '10/تجربی'), ('11/ریاضی', '11/ریاضی'), ('11/تجربی', '11/تجربی'), ('12/ریاضی', '12/ریاضی'), ('12/تجربی', '12/تجربی')], max_length=15),
        ),
    ]
