# Generated by Django 5.1.1 on 2025-02-24 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0001_initial'),
        ('Grades', '0003_remove_student_class_in_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Grades.student'),
        ),
    ]
