# Generated by Django 5.1.1 on 2024-12-09 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Attendance', '0001_initial'),
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='Authentication.student'),
        ),
        migrations.AlterUniqueTogether(
            name='absence',
            unique_together={('student', 'date')},
        ),
    ]
